os:
  - linux
  - osx
nodejs:
  - 0.10
  - 0.12
  - 4
  - 6
  - 8
sudo: false
language: node_js
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
notifications:
  email:
    - rod@vagg.org
install: npm install
script: npm test
